### ISSUE TITLE
miniwdl-lsf incompatible with memory specification via `-R "rusage[mem=]"`

### ISSUE THREAD

**Issue by Marc-Ruebsam** [adthrasher/miniwdl-lsf#4]
We are using miniwdl-lsf on a cluster that utilizes the LSF job scheduler. However, we've encountered an issue with job submission due to discrepancies in memory specification options.

### Problem: ###
miniwdl-lsf utilizes the `-M` flag for specifying memory requirements in job submissions. Our LSF cluster requires memory to be specified using the `-R "rusage[mem=]"` flag. Due to this incompatibility, submitted jobs are being rejected by the cluster. Resulting in:
```
+--------------------------------------------------+
| S U B M I S S I O N E R R O R                    |
+--------------------------------------------------+
| Your submission doesn't seem to contain a memory |
+--------------------------------------------------+
Request aborted by esub. Job not submitted.
```

#### Configurable switch: ####
Could a configuration switch be added to miniwdl-lsf that allows users to select between `-M` and `-R "rusage[mem=]"` based on their cluster requirements? This would provide flexibility and cater to diverse cluster setups.

#### Include both flags: ####
Alternatively, could miniwdl-lsf include both `-M` and `-R "rusage[mem=]"` flags in job submissions? This would work with our cluster, but I am unsure about other setups.

Thank you for your time and consideration.

### Versions: ###
```
$ miniwdl --version
miniwdl v1.11.1
miniwdl.plugin.container_backend        lsf_singularity = miniwdl_lsf:LSFSingularity    miniwdl-lsf 0.1.1
```

**Comment by adthrasher** [comment]
Thanks, @Marc-Ruebsam for the report (and the PR #5). I have taken a slightly different approach in #6. I have changed the submission to use `-R rusage` instead of `-M` and an option to set `-M`.  For your use case, the new version of `miniwdl-lsf` should produce the desired behavior without any further changes on your end.

I had missed this previously because our HPC group post-processes `bsub` invocations to ensure that the `-R rusage[mem=]` param and the value of `-M` match.

That said, I dug into this further in the LSF documentation, WDL spec, and `miniwdl` documentation. You may be aware of this already, but I'm going to write out my findings below for completeness.

LSF categorizes `-R` as a `resource` argument and `-M` as a `limit` argument. The [`-R rusage` parameter](https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=requirements-resource-requirement-strings) is a resource requirement or a minimum resource required by the job. In contrast, the [`-M` argument](https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=o-m) defines an upper limit for the resource usage for a given job.

The [WDL specification](https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#memory) specifies that `memory` is the "_minimum_ memory (RAM) required" for a task. 

Putting these together, the WDL `memory` runtime parameter corresponds to the `-R usage` parameter in LSF. So I have made that change in #6 . For users that want a hard limit, `miniwdl` has a configuration option `memory_limit_multiplier` which is described as 

>  A task's runtime.memory is used as a "reservation" to guide container scheduling, but isn't an
>  enforced limit unless memory_limit_multiplier is positive, which sets a hard limit of
>  memory_limit_multiplier*runtime.memory. Recommendation: if activating this, disable host swap.

I have added support for this configuration option as well. To reproduce the prior behavior of `miniwdl-lsf`, you can set `memory_limit_multiplier = 1` in the configuration. This will add the `-M` argument to the `bsub` command combining the WDL `memory` specification with the chosen multiplier, in addition to the `-R rusage` parameter.

**Comment by Marc-Ruebsam** [comment]
Thank you @adthrasher !
I was familiar with the LSF side of things, but not the WDL/miniwdl side. This is definitely the superior way to solve this.
